### ISSUE TITLE
Please add KDD 2019 paper

### ISSUE THREAD

**Issue by srijankr** [DeepGraphLearning/LiteratureDL4Graph#1]
Hi! 

Thank you for your incredible repository! 

Could you please add the following paper under "Node Representation Learning in Dynamic Graphs", "Node Representation Learning in Heterogeneous Graphs", and "Unsupervised Node Representation Learning"? It is an oral paper in the research track at SIGKDD 2019 and lies at the intersection of all three topics! 

Predicting Dynamic Embedding Trajectory in Temporal Interaction Networks. 
Srijan Kumar, Xikun Zhang, Jure Leskovec
25th ACM SIGKDD Conference on Knowledge Discovery and Data Mining, 2019.

Project website with new datasets and code: http://snap.stanford.edu/jodie

**Comment by Songweiping** [comment]
Nice work! Just added it.

**Comment by srijankr** [comment]
Thank you for adding the paper under "Node Representation Learning in Dynamic Graphs"! 

If you allow papers to be cross-listed under multiple categories, please also add it under the other two categories mentioned above :)

Thanks again for this excellent repo!
