### ISSUE TITLE
Add the AmpliGraph to "Graph Representation Learning Systems"

### ISSUE THREAD

**Issue by lukostaz** [DeepGraphLearning/LiteratureDL4Graph#2]
Thanks for the repo, super-useful pointers!

We have been working on [AmpliGraph](https://github.com/Accenture/AmpliGraph/),- a TensorFlow-based library for knowledge graph embeddings. Will you please add it to the list, under "Graph Representation Learning Systems"?

```
`AmpliGraph
<https://github.com/Accenture/AmpliGraph>`_
    | :author:`Luca Costabello, Sumit Pai, Chan Le Van, Rory McGrath, Nicholas McCarthy, Pedro Tabacof`
```

**Comment by KiddoZhu** [comment]
Yep AmpliGraph derserves a place. Just added it to the list.

**Comment by lukostaz** [comment]
Thanks @KiddoZhu ! 
Appreciate that - Keep up the good work!
