### ISSUE TITLE
Add MeshCNN [SIGGRAPH 2019]

### ISSUE THREAD

**Issue by ranahanocka** [DeepGraphLearning/LiteratureDL4Graph#3]
Hi,

Thanks a lot for making this great resource :)!

Could you please add our SIGGRAPH 2019 paper to the list? 
Here's the info: 

MeshCNN: A Network with an Edge
Rana Hanocka, Amir Hertz, Noa Fish, Raja Giryes, Shachar Fleishman, Daniel Cohen-Or
SIGGRAPH 2019 
[Project Page](https://ranahanocka.github.io/MeshCNN/)

**Comment by mnqu** [comment]
Nice work! We have added the paper : )

**Comment by ranahanocka** [comment]
@mnqu Thank you!
