### ISSUE TITLE
Please add Bayesian-GCN paper [AAAI 2019]

### ISSUE THREAD

**Issue by maggie0106** [DeepGraphLearning/LiteratureDL4Graph#4]
Hi,

Thank you very much for preparing this nice repo for graph related resources.

Could you please add our Bayesian-GCN [AAAI 2019] paper into the list? Essentially, we build on top of the GCN idea with topology exploration during the training. 

Here's the info:
"Bayesian graph convolutional neural networks for semi-supervised classification"
Yingxue Zhang, Soumyasundar Pal, Mark Coates, Deniz Üstebay.

thank you,
Yingxue

**Comment by Songweiping** [comment]
Nice work! Just added it!
