### ISSUE TITLE
Please add GraphTSNE [ICLR 2019 Workshop]

### ISSUE THREAD

**Issue by leowyy** [DeepGraphLearning/LiteratureDL4Graph#5]
Great work on the compilation of this incredibly useful resource! I notice that Section 6 on Visualization looks rather short. May I suggest adding our paper? TLDR: We propose a method for visualizing graph data by the minimization of the t-SNE loss with GCNs.   

[GraphTSNE: A Visualization Technique for Graph-Structured Data](https://arxiv.org/pdf/1904.06915.pdf)
Yao Yang Leow, Thomas Laurent, Xavier Bresson
ICLR 2019 Workshop
[https://github.com/leowyy/GraphTSNE](https://github.com/leowyy/GraphTSNE)

**Comment by Songweiping** [comment]
Nice work! Get it done!
