### ISSUE TITLE
Additions to Bioinformatics Section

### ISSUE THREAD

**Issue by ali-kishk** [DeepGraphLearning/LiteratureDL4Graph#9]
`Detecting drug-drug interactions using artificial neural networks and classic graph similarity measures
<https://arxiv.org/pdf/1903.04571.pdf>`_
    | :author:`Shtar, Guy, Lior Rokach, and Bracha Shapira`
    | :venue:`arXiv preprint arXiv:1903.04571 (2019)`

`PGCN: Disease gene prioritization by disease and gene embedding through graph convolutional neural networks
<https://www.biorxiv.org/content/biorxiv/early/2019/01/28/532226.full.pdf>`_
    | :author:`Li, Yu, et al`
    | :venue:`bioRxiv (2019)`

`Identifying Protein-Protein Interaction using Tree LSTM and Structured Attention
<https://ieeexplore.ieee.org/abstract/document/8665584>`_
    | :author:`Ahmed, Mahtab, et al`
    | :venue:`2019 IEEE 13th International Conference on Semantic Computing (ICSC). IEEE, 2019`

**Comment by mnqu** [comment]
Thanks for pointing out those papers! All of them are great works, and we have uploaded them.
